using System;
using System.Collections.Generic;
using System.Data;
using System.Data.SQLite;
using System.Globalization;
using System.IO;
using System.IO.Compression;
using System.Text;
using System.Threading;
using System.Threading.Tasks;
using System.Xml;

namespace BmsSerialDemo
{
    public sealed partial class SampleStore
    {
        sealed class ExportSample
        {
            public long Id, Round; public DateTime Utc; public int Address,Pack,Soc,Soh,Cycles,Voltage,Current,Remaining,Total; public int? BalanceLow,BalanceHigh,Humidity,Period;
            public int[] Cells=new int[0],Temps=new int[0]; public bool[] HasCell=new bool[0],HasTemp=new bool[0];
        }
        sealed class ExportAlarm { public long Id,Round; public DateTime Utc; public int Address,Pack; public int? Period; public string Text; public byte[] Payload; }
        internal sealed class ExportBounds { public long Samples,Alarms,Policies; public int CellCount,TempCount,AlarmTextParts; }

        public async Task<XlsxExportResult> ExportXlsxAsync(DateTime fromUtc,DateTime toUtc,int pack,string parentDirectory,IProgress<XlsxExportProgress> progress,CancellationToken cancellationToken)
        {
            if(String.IsNullOrWhiteSpace(parentDirectory))throw new ArgumentException("请选择导出目录","parentDirectory");
            if(toUtc<=fromUtc)throw new ArgumentException("结束时间必须晚于开始时间");
            ExportNaming.VerifyDestination(parentDirectory);
            if(!await ExportGate.WaitAsync(0,cancellationToken).ConfigureAwait(false))throw new InvalidOperationException("已有CSV或XLSX导出任务正在进行，请稍后重试。");
            try
            {
            ExportBounds b=new ExportBounds();
            await Submit(delegate(SQLiteConnection c,SQLiteTransaction t){
                b.Samples=ScalarLong(c,t,"SELECT COALESCE(MAX(id),0) FROM samples");b.Alarms=ScalarLong(c,t,"SELECT COALESCE(MAX(id),0) FROM alarm_observations");b.Policies=ScalarLong(c,t,"SELECT COALESCE(MAX(id),0) FROM recording_policies");
                b.CellCount=0;b.TempCount=0;b.AlarmTextParts=1;
            },false).ConfigureAwait(false);
            return await Task.Run(delegate{return ExportXlsxWorker(fromUtc.ToUniversalTime(),toUtc.ToUniversalTime(),pack,parentDirectory,b,progress,cancellationToken);},cancellationToken).ConfigureAwait(false);
            }
            finally { ExportGate.Release(); }
        }
        internal async Task<XlsxExportResult> ExportXlsxFrozenAsync(DateTime fromUtc,DateTime toUtc,int pack,string parentDirectory,ExportBounds bounds,IProgress<XlsxExportProgress> progress,CancellationToken cancellationToken)
        {
            return await Task.Run(delegate{return ExportXlsxWorker(fromUtc.ToUniversalTime(),toUtc.ToUniversalTime(),pack,parentDirectory,bounds,progress,cancellationToken,true);},cancellationToken).ConfigureAwait(false);
        }
        static long ScalarLong(SQLiteConnection c,SQLiteTransaction t,string sql){using(SQLiteCommand q=new SQLiteCommand(sql,c,t))return Convert.ToInt64(q.ExecuteScalar(),CultureInfo.InvariantCulture);}
        XlsxExportResult ExportXlsxWorker(DateTime fromUtc,DateTime toUtc,int pack,string parent,ExportBounds bounds,IProgress<XlsxExportProgress> progress,CancellationToken token,bool compactOutput=false)
        {
            Directory.CreateDirectory(parent);string stem=ExportNaming.Stem(source,pack,fromUtc,toUtc);string final=compactOutput?Path.Combine(Path.GetFullPath(parent),".db-export-"+Guid.NewGuid().ToString("N").Substring(0,12)):ExportNaming.AvailableDirectory(parent,stem);
            if((final+"\\"+stem+"_001.xlsx").Length>245)throw new PathTooLongException("导出路径过长，请选择更短的输出目录。");string temp=ExportNaming.CreateWorkDirectory();List<string> files=new List<string>();long samples=0,alarms=0,policies=0,done=0;long sampleAfter=0,alarmAfter=0,policyAfter=0;string readCs="Data Source="+dbPath+";Version=3;Read Only=True;BusyTimeout=5000;";
            try
            {
                CheckExportDiskSpace(parent,progress);
                using(SQLiteConnection c=new SQLiteConnection(readCs)){c.Open();using(SQLiteCommand prag=new SQLiteCommand("PRAGMA cache_size=-8192; PRAGMA temp_store=FILE",c))prag.ExecuteNonQuery();DiscoverDimensions(c,bounds,fromUtc,toUtc,pack,progress,token);
                    long matchSamples=CountExportRows(c,"samples","received_utc_ms",bounds.Samples,fromUtc,toUtc,pack),matchAlarms=CountExportRows(c,"alarm_observations","received_utc_ms",bounds.Alarms,fromUtc,toUtc,pack),matchPolicies=CountExportRows(c,"recording_policies","changed_utc_ms",bounds.Policies,fromUtc,toUtc,0);
                    if(matchSamples+matchAlarms+matchPolicies==0)throw new InvalidOperationException("所选时间范围和 Pack 没有可导出的数据。");
                    bool moreSamples=bounds.Samples>=0,moreAlarms=bounds.Alarms>=0,morePolicies=bounds.Policies>=0;int volume=0;
                    while(moreSamples||moreAlarms||morePolicies)
                    {
                        token.ThrowIfCancellationRequested();CheckExportDiskSpace(temp,progress);volume++;string file=stem+"_"+volume.ToString("000",CultureInfo.InvariantCulture)+".xlsx";string path=Path.Combine(temp,file);
                        using(XlsxVolume x=new XlsxVolume(path,bounds.CellCount,bounds.TempCount,bounds.AlarmTextParts,volume,source,dbPath))
                        {
                            int inFileSamples=0,inFileAlarms=0;List<ExportSample> batch;
                            int sampleCost=Math.Max(1,18+bounds.CellCount+bounds.TempCount);int sampleLimit=(int)Math.Min(100000,5000000L/sampleCost);
                            while(moreSamples&&inFileSamples<sampleLimit&&inFileSamples+inFileAlarms<200000)
                            {
                                token.ThrowIfCancellationRequested();int take=Math.Min(200,Math.Min(sampleLimit-inFileSamples,200000-inFileSamples-inFileAlarms));batch=ReadSampleBatch(c,sampleAfter,bounds.Samples,fromUtc,toUtc,pack,take);if(batch.Count==0){moreSamples=false;break;}sampleAfter=batch[batch.Count-1].Id;ReadSampleChildren(c,batch);
                                foreach(ExportSample s in batch){token.ThrowIfCancellationRequested();x.WriteSample(s);samples++;done++;inFileSamples++;}Report(progress,"正在导出实时数据",done,0);
                            }
                            List<ExportAlarm> ab;
                            int alarmCost=8+bounds.AlarmTextParts;int alarmLimit=(int)Math.Min(100000,Math.Max(0,(5000000L-inFileSamples*(long)sampleCost)/alarmCost));
                            while(moreAlarms&&inFileAlarms<alarmLimit&&inFileSamples+inFileAlarms<200000)
                            {
                                token.ThrowIfCancellationRequested();int take=Math.Min(200,Math.Min(alarmLimit-inFileAlarms,200000-inFileSamples-inFileAlarms));ab=ReadAlarmBatch(c,alarmAfter,bounds.Alarms,fromUtc,toUtc,pack,take);if(ab.Count==0){moreAlarms=false;break;}alarmAfter=ab[ab.Count-1].Id;
                                foreach(ExportAlarm a in ab){token.ThrowIfCancellationRequested();x.WriteAlarm(a);alarms++;done++;inFileAlarms++;}Report(progress,"正在导出告警",done,0);
                            }
                            int inFilePolicies=0;int policyLimit=(int)Math.Min(Math.Min(100000,200000-inFileSamples-inFileAlarms),Math.Max(0,(5000000L-inFileSamples*(long)sampleCost-inFileAlarms*(long)alarmCost)/5));while(morePolicies&&inFilePolicies<policyLimit){token.ThrowIfCancellationRequested();List<string[]> pol=ReadPolicyBatch(c,policyAfter,bounds.Policies,fromUtc,toUtc,Math.Min(200,policyLimit-inFilePolicies));if(pol.Count==0){morePolicies=false;break;}foreach(string[] row in pol){token.ThrowIfCancellationRequested();policyAfter=Convert.ToInt64(row[0],CultureInfo.InvariantCulture);x.WritePolicy(row);policies++;inFilePolicies++;}}
                            x.WriteMeta(fromUtc,toUtc,pack,bounds.Samples,bounds.Alarms,inFileSamples,inFileAlarms,inFileSamples*sampleCost+inFileAlarms*alarmCost+inFilePolicies*5);
                        }
                        files.Add(file);
                    }
                }
                token.ThrowIfCancellationRequested();File.WriteAllText(Path.Combine(temp,stem+"_清单.txt"),"本次完整导出\r\n时间范围（本地，开始含结束不含）="+fromUtc.ToLocalTime().ToString("yyyy-MM-dd HH:mm:ss zzz",CultureInfo.InvariantCulture)+" — "+toUtc.ToLocalTime().ToString("yyyy-MM-dd HH:mm:ss zzz",CultureInfo.InvariantCulture)+"\r\n数据源="+(source=="simulation"?"模拟":"真实")+"\r\nPack="+(pack==0?"全部":pack.ToString(CultureInfo.InvariantCulture))+"\r\n"+String.Join("\r\n",files.ToArray())+"\r\n实时数据行数="+samples+"\r\n告警行数="+alarms+"\r\n策略事件行数="+policies+"\r\n",new UTF8Encoding(true));ExportNaming.PublishDirectory(temp,parent,final,token);Report(progress,"导出完成",done,done);
                return new XlsxExportResult{OutputDirectory=final,Files=files.ToArray(),FileCount=files.Count,SampleRows=samples,AlarmRows=alarms,PolicyRows=policies};
            }
            finally{ExportNaming.TryDeleteDirectory(temp);}
        }
        static void Report(IProgress<XlsxExportProgress> p,string phase,long done,long total){if(p!=null)p.Report(new XlsxExportProgress{Phase=phase,CompletedRows=done,TotalRows=total});}
        static long CountExportRows(SQLiteConnection c,string table,string timeColumn,long upper,DateTime fromUtc,DateTime toUtc,int pack){if(upper<0||!TableExists(c,table))return 0;using(SQLiteCommand q=new SQLiteCommand("SELECT COUNT(*) FROM "+table+" WHERE id<=@u AND "+timeColumn+">=@f AND "+timeColumn+"<@to"+(table=="recording_policies"?"":" AND (@p=0 OR pack=@p)"),c)){q.Parameters.AddWithValue("@u",upper);q.Parameters.AddWithValue("@f",ToMs(fromUtc));q.Parameters.AddWithValue("@to",ToMs(toUtc));if(table!="recording_policies")q.Parameters.AddWithValue("@p",pack);return Convert.ToInt64(q.ExecuteScalar(),CultureInfo.InvariantCulture);}}
        static void CheckExportDiskSpace(string path,IProgress<XlsxExportProgress> progress){string root=Path.GetPathRoot(Path.GetFullPath(path));long free=new DriveInfo(root).AvailableFreeSpace;if(free<100L*1024*1024)throw new IOException("XLSX输出卷可用空间低于100 MiB；导出已停止。");if(free<1024L*1024*1024)Report(progress,"输出卷可用空间低于1 GiB，导出仍在继续",0,0);}
        static List<ExportSample> ReadSampleBatch(SQLiteConnection c,long after,long upper,DateTime f,DateTime to,int pack,int limit)
        {
            List<ExportSample> a=new List<ExportSample>();string sql="SELECT id,received_utc_ms,address,pack,soc,soh,cycles,voltage_cV,current_cA,remaining_cAh,total_cAh,"+ColumnOrNull(c,"samples","balance_low_raw")+","+ColumnOrNull(c,"samples","balance_high_raw")+","+ColumnOrNull(c,"samples","humidity_pct")+","+ColumnOrNull(c,"samples","acquisition_round")+","+ColumnOrNull(c,"samples","period_seconds")+" FROM samples WHERE id>@after AND id<=@upper AND received_utc_ms>=@f AND received_utc_ms<@to AND (@p=0 OR pack=@p) ORDER BY id LIMIT @n";using(SQLiteCommand q=new SQLiteCommand(sql,c))
            {q.Parameters.AddWithValue("@after",after);q.Parameters.AddWithValue("@upper",upper);q.Parameters.AddWithValue("@f",ToMs(f));q.Parameters.AddWithValue("@to",ToMs(to));q.Parameters.AddWithValue("@p",pack);q.Parameters.AddWithValue("@n",limit);using(SQLiteDataReader r=q.ExecuteReader())while(r.Read())a.Add(new ExportSample{Id=r.GetInt64(0),Utc=FromMs(r.GetInt64(1)),Address=r.GetInt32(2),Pack=r.GetInt32(3),Soc=r.GetInt32(4),Soh=r.GetInt32(5),Cycles=r.GetInt32(6),Voltage=r.GetInt32(7),Current=r.GetInt32(8),Remaining=r.GetInt32(9),Total=r.GetInt32(10),BalanceLow=r.IsDBNull(11)?(int?)null:r.GetInt32(11),BalanceHigh=r.IsDBNull(12)?(int?)null:r.GetInt32(12),Humidity=r.IsDBNull(13)?(int?)null:r.GetInt32(13),Round=r.IsDBNull(14)?0:r.GetInt64(14),Period=r.IsDBNull(15)?(int?)null:r.GetInt32(15),Cells=new int[48],Temps=new int[32],HasCell=new bool[48],HasTemp=new bool[32]});}
            return a;
        }
        static void ReadSampleChildren(SQLiteConnection c,List<ExportSample> rows)
        {
            if(rows.Count==0)return;StringBuilder ids=new StringBuilder();Dictionary<long,ExportSample> map=new Dictionary<long,ExportSample>();foreach(ExportSample r in rows){if(ids.Length>0)ids.Append(',');ids.Append(r.Id.ToString(CultureInfo.InvariantCulture));map.Add(r.Id,r);}
            if(TableExists(c,"cell_values"))using(SQLiteCommand q=new SQLiteCommand("SELECT sample_id,cell_index,millivolts FROM cell_values WHERE sample_id IN ("+ids+") ORDER BY sample_id,cell_index",c))using(SQLiteDataReader r=q.ExecuteReader())while(r.Read()){ExportSample s=map[r.GetInt64(0)];int n=r.GetInt32(1);if(n<1||n>48)throw new InvalidDataException("样本电芯编号超出协议上限");s.Cells[n-1]=r.GetInt32(2);s.HasCell[n-1]=true;}
            if(TableExists(c,"temperature_values"))using(SQLiteCommand q=new SQLiteCommand("SELECT sample_id,measurement_index,celsius FROM temperature_values WHERE sample_id IN ("+ids+") ORDER BY sample_id,measurement_index",c))using(SQLiteDataReader r=q.ExecuteReader())while(r.Read()){ExportSample s=map[r.GetInt64(0)];int n=r.GetInt32(1);if(n<1||n>32)throw new InvalidDataException("温度测点编号超出协议上限");s.Temps[n-1]=r.GetInt32(2);s.HasTemp[n-1]=true;}
        }
        static List<ExportAlarm> ReadAlarmBatch(SQLiteConnection c,long after,long upper,DateTime f,DateTime to,int pack,int limit)
        {string sql="SELECT id,received_utc_ms,address,pack,decoded_text,payload,"+ColumnOrNull(c,"alarm_observations","acquisition_round")+","+ColumnOrNull(c,"alarm_observations","period_seconds")+" FROM alarm_observations WHERE id>@after AND id<=@upper AND received_utc_ms>=@f AND received_utc_ms<@to AND (@p=0 OR pack=@p) ORDER BY id LIMIT @n";List<ExportAlarm>a=new List<ExportAlarm>();using(SQLiteCommand q=new SQLiteCommand(sql,c)){q.Parameters.AddWithValue("@after",after);q.Parameters.AddWithValue("@upper",upper);q.Parameters.AddWithValue("@f",ToMs(f));q.Parameters.AddWithValue("@to",ToMs(to));q.Parameters.AddWithValue("@p",pack);q.Parameters.AddWithValue("@n",limit);using(SQLiteDataReader r=q.ExecuteReader())while(r.Read())a.Add(new ExportAlarm{Id=r.GetInt64(0),Utc=FromMs(r.GetInt64(1)),Address=r.GetInt32(2),Pack=r.GetInt32(3),Text=r.IsDBNull(4)?"":r.GetString(4),Payload=r.IsDBNull(5)?new byte[0]:(byte[])r[5],Round=r.IsDBNull(6)?0:r.GetInt64(6),Period=r.IsDBNull(7)?(int?)null:r.GetInt32(7)});}return a;}
        static void DiscoverDimensions(SQLiteConnection c,ExportBounds b,DateTime f,DateTime to,int pack,IProgress<XlsxExportProgress> progress,CancellationToken token)
        {
            bool hasCells=TableExists(c,"cell_values"),hasTemps=TableExists(c,"temperature_values");
            long after=0,seen=0;
            while(b.Samples>=0){token.ThrowIfCancellationRequested();List<long> ids=new List<long>(200);using(SQLiteCommand q=new SQLiteCommand("SELECT id FROM samples WHERE id>@a AND id<=@u AND received_utc_ms>=@f AND received_utc_ms<@to AND (@p=0 OR pack=@p) ORDER BY id LIMIT 200",c)){q.Parameters.AddWithValue("@a",after);q.Parameters.AddWithValue("@u",b.Samples);q.Parameters.AddWithValue("@f",ToMs(f));q.Parameters.AddWithValue("@to",ToMs(to));q.Parameters.AddWithValue("@p",pack);using(SQLiteDataReader r=q.ExecuteReader())while(r.Read())ids.Add(r.GetInt64(0));}if(ids.Count==0)break;after=ids[ids.Count-1];seen+=ids.Count;string key=IdList(ids);
                if(hasCells)using(SQLiteCommand q=new SQLiteCommand("SELECT COALESCE(MAX(cell_index),0) FROM cell_values WHERE sample_id IN ("+key+")",c))b.CellCount=Math.Max(b.CellCount,Convert.ToInt32(q.ExecuteScalar(),CultureInfo.InvariantCulture));
                if(hasTemps)using(SQLiteCommand q=new SQLiteCommand("SELECT COALESCE(MAX(measurement_index),0) FROM temperature_values WHERE sample_id IN ("+key+")",c))b.TempCount=Math.Max(b.TempCount,Convert.ToInt32(q.ExecuteScalar(),CultureInfo.InvariantCulture));Report(progress,"正在检查字段范围",seen,0);
            }
            after=0;int maxParts=1;while(b.Alarms>=0){token.ThrowIfCancellationRequested();int n=0;long last=after;using(SQLiteCommand q=new SQLiteCommand("SELECT id,decoded_text FROM alarm_observations WHERE id>@a AND id<=@u AND received_utc_ms>=@f AND received_utc_ms<@to AND (@p=0 OR pack=@p) ORDER BY id LIMIT 200",c)){q.Parameters.AddWithValue("@a",after);q.Parameters.AddWithValue("@u",b.Alarms);q.Parameters.AddWithValue("@f",ToMs(f));q.Parameters.AddWithValue("@to",ToMs(to));q.Parameters.AddWithValue("@p",pack);using(SQLiteDataReader r=q.ExecuteReader())while(r.Read()){n++;last=r.GetInt64(0);string text=r.IsDBNull(1)?"":r.GetString(1);maxParts=Math.Max(maxParts,SafeChunkCount(XlsxVolume.XmlSafe(text)));}}if(n==0)break;after=last;token.ThrowIfCancellationRequested();}
            b.AlarmTextParts=maxParts;if(b.CellCount>48||b.TempCount>32)throw new InvalidDataException("数据库字段编号超出协议上限");if(b.AlarmTextParts>16)throw new InvalidDataException("告警文本超过XLSX最多16列的无损分片范围");
        }
        static int SafeChunkCount(string text){int n=0,offset=0;while(offset<text.Length){int length=Math.Min(32767,text.Length-offset);if(offset+length<text.Length&&length>0&&Char.IsHighSurrogate(text[offset+length-1])&&Char.IsLowSurrogate(text[offset+length]))length--;offset+=length;n++;}return Math.Max(1,n);}
        static bool TableExists(SQLiteConnection c,string name){using(SQLiteCommand q=new SQLiteCommand("SELECT 1 FROM sqlite_master WHERE type='table' AND name=@n",c)){q.Parameters.AddWithValue("@n",name);return q.ExecuteScalar()!=null;}}
        static string ColumnOrNull(SQLiteConnection c,string table,string column){using(SQLiteCommand q=new SQLiteCommand("PRAGMA table_info("+table+")",c))using(SQLiteDataReader r=q.ExecuteReader())while(r.Read())if(String.Equals(r.GetString(1),column,StringComparison.OrdinalIgnoreCase))return column;return "NULL";}
        static string IdList(List<long> ids){StringBuilder b=new StringBuilder();foreach(long id in ids){if(b.Length>0)b.Append(',');b.Append(id.ToString(CultureInfo.InvariantCulture));}return b.ToString();}
        static List<string[]> ReadPolicyBatch(SQLiteConnection c,long after,long upper,DateTime f,DateTime to,int limit){List<string[]>a=new List<string[]>();using(SQLiteCommand q=new SQLiteCommand("SELECT id,changed_utc_ms,period_seconds,session_id FROM recording_policies WHERE id>@a AND id<=@u AND changed_utc_ms>=@f AND changed_utc_ms<@to ORDER BY id LIMIT @n",c)){q.Parameters.AddWithValue("@a",after);q.Parameters.AddWithValue("@u",upper);q.Parameters.AddWithValue("@f",ToMs(f));q.Parameters.AddWithValue("@to",ToMs(to));q.Parameters.AddWithValue("@n",limit);using(SQLiteDataReader r=q.ExecuteReader())while(r.Read())a.Add(new[]{r.GetInt64(0).ToString(CultureInfo.InvariantCulture),FromMs(r.GetInt64(1)).ToString("o",CultureInfo.InvariantCulture),r.GetInt32(2).ToString(CultureInfo.InvariantCulture),r.GetInt32(3).ToString(CultureInfo.InvariantCulture)});}return a;}

        sealed class XlsxVolume : IDisposable
        {
            ZipArchive z;int cells,temps,alarmParts,vol;long mainRows,alarmRows,policyRows;XmlWriter main,alarm,policy,meta;string src,packagePath,database;string[] sheetFiles;
            public XlsxVolume(string path,int c,int t,int ap,int v,string source,string databasePath){cells=Math.Max(0,c);temps=Math.Max(0,t);alarmParts=Math.Max(1,ap);vol=v;src=source=="simulation"?"模拟":"真实";database=databasePath;packagePath=path;sheetFiles=new[]{path+".s1.xml",path+".s2.xml",path+".s3.xml",path+".s4.xml"};z=ZipFile.Open(path,ZipArchiveMode.Create);WriteStatic("[Content_Types].xml",ContentTypes());WriteStatic("_rels/.rels",RootRels());WriteStatic("xl/styles.xml",Styles());WriteStatic("xl/workbook.xml",Workbook());WriteStatic("xl/_rels/workbook.xml.rels",WorkbookRels());main=Sheet(sheetFiles[0]);alarm=Sheet(sheetFiles[1]);policy=Sheet(sheetFiles[2]);meta=Sheet(sheetFiles[3]);List<string> h=new List<string>{"ID","采集时间（本地）","来源","地址","Pack","总压 (V)","电流 (A)","SOC (%)","SOH (%)","剩余容量 (Ah)","总容量 (Ah)","循环次数","均衡低位原始值","均衡高位原始值","湿度 (%)","采集轮","采集间隔（秒）"};for(int i=1;i<=cells;i++)h.Add("电芯 "+i+" (mV)");for(int i=1;i<=temps;i++)h.Add("温度 "+i+" (℃)");StartSheet(main,h.ToArray());StartSheet(alarm,AlarmHeaders(alarmParts));StartSheet(policy,new[]{"事件ID","变更时间（本地）","采集间隔（秒）","会话ID"});StartSheet(meta,new[]{"项目","值"});}
            string[] AlarmHeaders(int n){List<string>a=new List<string>{"告警ID","采集时间（本地）","地址","Pack","采集轮","采集间隔（秒）"};for(int i=1;i<=n;i++)a.Add("告警文本 "+i);a.Add("原始载荷 HEX");return a.ToArray();}
            XmlWriter Sheet(string path){return XmlWriter.Create(path,new XmlWriterSettings{Encoding=new UTF8Encoding(false),CloseOutput=true});}
            void WriteStatic(string name,string xml){using(Stream s=z.CreateEntry(name,CompressionLevel.Optimal).Open())using(StreamWriter w=new StreamWriter(s,new UTF8Encoding(false)))w.Write(xml);}
            void StartSheet(XmlWriter w,string[] headers){w.WriteStartDocument();w.WriteStartElement("worksheet","http://schemas.openxmlformats.org/spreadsheetml/2006/main");w.WriteStartElement("sheetViews");w.WriteStartElement("sheetView");w.WriteAttributeString("workbookViewId","0");w.WriteStartElement("pane");w.WriteAttributeString("ySplit","1");w.WriteAttributeString("topLeftCell","A2");w.WriteAttributeString("activePane","bottomLeft");w.WriteAttributeString("state","frozen");w.WriteEndElement();w.WriteEndElement();w.WriteEndElement();w.WriteStartElement("cols");for(int i=1;i<=headers.Length;i++){w.WriteStartElement("col");w.WriteAttributeString("min",i.ToString());w.WriteAttributeString("max",i.ToString());w.WriteAttributeString("width",i==1?"14":"18");w.WriteAttributeString("customWidth","1");w.WriteEndElement();}w.WriteEndElement();w.WriteStartElement("sheetData");WriteRow(w,1,headers);}
            void BeginRow(XmlWriter w,int row){w.WriteStartElement("row");w.WriteAttributeString("r",row.ToString(CultureInfo.InvariantCulture));}
            void WriteRow(XmlWriter w,int row,string[] text){BeginRow(w,row);for(int i=0;i<text.Length;i++)WriteText(w,i+1,row,text[i]);w.WriteEndElement();}
            void WriteText(XmlWriter w,int col,int row,string text){if(String.IsNullOrEmpty(text))return;w.WriteStartElement("c");w.WriteAttributeString("r",Col(col)+row.ToString(CultureInfo.InvariantCulture));w.WriteAttributeString("t","inlineStr");w.WriteStartElement("is");w.WriteStartElement("t");w.WriteAttributeString("xml","space","http://www.w3.org/XML/1998/namespace","preserve");w.WriteString(XmlSafe(text));w.WriteEndElement();w.WriteEndElement();w.WriteEndElement();}
            void WriteNumber(XmlWriter w,int col,int row,string value,int style=0){if(String.IsNullOrEmpty(value))return;w.WriteStartElement("c");w.WriteAttributeString("r",Col(col)+row.ToString(CultureInfo.InvariantCulture));if(style>0)w.WriteAttributeString("s",style.ToString());w.WriteElementString("v","http://schemas.openxmlformats.org/spreadsheetml/2006/main",value);w.WriteEndElement();}
            void WriteDate(XmlWriter w,int col,int row,DateTime dt){double serial=(dt-new DateTime(1899,12,30,0,0,0,DateTimeKind.Utc)).TotalDays;WriteNumber(w,col,row,serial.ToString("0.0000000000",CultureInfo.InvariantCulture),1);}
            public void WriteSample(ExportSample s){int r=(int)++mainRows+1,k=1;BeginRow(main,r);WriteNumber(main,k++,r,s.Id.ToString());WriteDate(main,k++,r,s.Utc.ToLocalTime());WriteText(main,k++,r,src);WriteNumber(main,k++,r,s.Address.ToString());WriteNumber(main,k++,r,s.Pack.ToString());WriteNumber(main,k++,r,(s.Voltage/100.0).ToString("0.00",CultureInfo.InvariantCulture));WriteNumber(main,k++,r,(s.Current/100.0).ToString("0.00",CultureInfo.InvariantCulture));WriteNumber(main,k++,r,s.Soc.ToString());WriteNumber(main,k++,r,s.Soh.ToString());WriteNumber(main,k++,r,(s.Remaining/100.0).ToString("0.00",CultureInfo.InvariantCulture));WriteNumber(main,k++,r,(s.Total/100.0).ToString("0.00",CultureInfo.InvariantCulture));WriteNumber(main,k++,r,s.Cycles.ToString());WriteOpt(main,k++,r,s.BalanceLow);WriteOpt(main,k++,r,s.BalanceHigh);WriteOpt(main,k++,r,s.Humidity);WriteOpt(main,k++,r,s.Round>0?(long?)s.Round:null);WriteOpt(main,k++,r,s.Period);for(int i=0;i<cells;i++)WriteOpt(main,k++,r,s.HasCell[i]?(int?)s.Cells[i]:null);for(int i=0;i<temps;i++)WriteOpt(main,k++,r,s.HasTemp[i]?(int?)s.Temps[i]:null);main.WriteEndElement();}
            void WriteOpt(XmlWriter w,int c,int r,int? n){if(n.HasValue)WriteNumber(w,c,r,n.Value.ToString(CultureInfo.InvariantCulture));}void WriteOpt(XmlWriter w,int c,int r,long? n){if(n.HasValue)WriteNumber(w,c,r,n.Value.ToString(CultureInfo.InvariantCulture));}
            public void WriteAlarm(ExportAlarm a){int r=(int)++alarmRows+1,k=1;BeginRow(alarm,r);WriteNumber(alarm,k++,r,a.Id.ToString());WriteDate(alarm,k++,r,a.Utc.ToLocalTime());WriteNumber(alarm,k++,r,a.Address.ToString());WriteNumber(alarm,k++,r,a.Pack.ToString());WriteOpt(alarm,k++,r,a.Round>0?(long?)a.Round:null);WriteOpt(alarm,k++,r,a.Period);string txt=XmlSafe(a.Text??"");if(txt.Length>32767*alarmParts)throw new InvalidDataException("告警文本超过XLSX分列长度限制；数据库原文已保留，本次结果未发布");int offset=0;for(int i=0;i<alarmParts;i++){int length=Math.Min(32767,txt.Length-offset);if(offset+length<txt.Length&&length>0&&Char.IsHighSurrogate(txt[offset+length-1])&&Char.IsLowSurrogate(txt[offset+length]))length--;WriteText(alarm,k++,r,length<=0?"":txt.Substring(offset,length));offset+=length;}if(offset<txt.Length)throw new InvalidDataException("告警文本分片不完整；数据库原文已保留，本次结果未发布");WriteText(alarm,k,r,BitConverter.ToString(a.Payload??new byte[0]).Replace("-",""));alarm.WriteEndElement();}
            public void WritePolicy(string[] p){int r=(int)++policyRows+1;BeginRow(policy,r);WriteNumber(policy,1,r,p[0]);DateTime utc=DateTime.Parse(p[1],CultureInfo.InvariantCulture,DateTimeStyles.RoundtripKind);WriteDate(policy,2,r,utc.ToLocalTime());WriteNumber(policy,3,r,p[2]);WriteNumber(policy,4,r,p[3]);policy.WriteEndElement();}
            public void WriteMeta(DateTime f,DateTime t,int pack,long upperS,long upperA,int s,int a,long cellCount){string[][] rows={new[]{"数据源",src},new[]{"数据库",database},new[]{"时间范围（本地，开始含结束不含）",f.ToLocalTime().ToString("yyyy-MM-dd HH:mm:ss zzz",CultureInfo.InvariantCulture)+" — "+t.ToLocalTime().ToString("yyyy-MM-dd HH:mm:ss zzz",CultureInfo.InvariantCulture)},new[]{"时间语义","时间按采集电脑接收时刻筛选；表格日期显示本地时间，不是设备时钟"},new[]{"Pack",pack==0?"全部":pack.ToString(CultureInfo.InvariantCulture)},new[]{"固定样本ID上界",upperS.ToString(CultureInfo.InvariantCulture)},new[]{"固定告警ID上界",upperA.ToString(CultureInfo.InvariantCulture)},new[]{"本文件实时数据行数",s.ToString(CultureInfo.InvariantCulture)},new[]{"本文件告警行数",a.ToString(CultureInfo.InvariantCulture)},new[]{"本文件数据单元格估算",cellCount.ToString(CultureInfo.InvariantCulture)},new[]{"文本规则","所有设备文本均以inlineStr写入；XML非法控制字符以[U+XXXX]标记，原始载荷保留数据库"},new[]{"分卷",vol.ToString(CultureInfo.InvariantCulture)}};int r=1;foreach(string[] x in rows){BeginRow(meta,r);WriteText(meta,1,r,x[0]);WriteText(meta,2,r,x[1]);meta.WriteEndElement();r++;}}
            internal static string XmlSafe(string s){StringBuilder b=new StringBuilder(s.Length);for(int i=0;i<s.Length;i++){char ch=s[i];if(ch==9||ch==10||ch==13||(ch>=32&&ch<=0xD7FF)||(ch>=0xE000&&ch<=0xFFFD))b.Append(ch);else if(Char.IsHighSurrogate(ch)&&i+1<s.Length&&Char.IsLowSurrogate(s[i+1])){b.Append(ch);b.Append(s[++i]);}else b.Append("[U+").Append(((int)ch).ToString("X4",CultureInfo.InvariantCulture)).Append(']');}return b.ToString();}
            static string Col(int n){StringBuilder b=new StringBuilder();while(n>0){n--;b.Insert(0,(char)('A'+n%26));n/=26;}return b.ToString();}
            static string ContentTypes(){return "<?xml version=\"1.0\" encoding=\"UTF-8\"?><Types xmlns=\"http://schemas.openxmlformats.org/package/2006/content-types\"><Default Extension=\"rels\" ContentType=\"application/vnd.openxmlformats-package.relationships+xml\"/><Default Extension=\"xml\" ContentType=\"application/xml\"/><Override PartName=\"/xl/workbook.xml\" ContentType=\"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet.main+xml\"/><Override PartName=\"/xl/styles.xml\" ContentType=\"application/vnd.openxmlformats-officedocument.spreadsheetml.styles+xml\"/><Override PartName=\"/xl/worksheets/sheet1.xml\" ContentType=\"application/vnd.openxmlformats-officedocument.spreadsheetml.worksheet+xml\"/><Override PartName=\"/xl/worksheets/sheet2.xml\" ContentType=\"application/vnd.openxmlformats-officedocument.spreadsheetml.worksheet+xml\"/><Override PartName=\"/xl/worksheets/sheet3.xml\" ContentType=\"application/vnd.openxmlformats-officedocument.spreadsheetml.worksheet+xml\"/><Override PartName=\"/xl/worksheets/sheet4.xml\" ContentType=\"application/vnd.openxmlformats-officedocument.spreadsheetml.worksheet+xml\"/></Types>";}
            static string RootRels(){return "<?xml version=\"1.0\" encoding=\"UTF-8\"?><Relationships xmlns=\"http://schemas.openxmlformats.org/package/2006/relationships\"><Relationship Id=\"rId1\" Type=\"http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument\" Target=\"xl/workbook.xml\"/></Relationships>";}
            static string Workbook(){return "<?xml version=\"1.0\" encoding=\"UTF-8\"?><workbook xmlns=\"http://schemas.openxmlformats.org/spreadsheetml/2006/main\" xmlns:r=\"http://schemas.openxmlformats.org/officeDocument/2006/relationships\"><sheets><sheet name=\"实时数据\" sheetId=\"1\" r:id=\"rId1\"/><sheet name=\"告警\" sheetId=\"2\" r:id=\"rId2\"/><sheet name=\"策略事件\" sheetId=\"3\" r:id=\"rId3\"/><sheet name=\"元信息\" sheetId=\"4\" r:id=\"rId4\"/></sheets></workbook>";}
            static string WorkbookRels(){return "<?xml version=\"1.0\" encoding=\"UTF-8\"?><Relationships xmlns=\"http://schemas.openxmlformats.org/package/2006/relationships\"><Relationship Id=\"rId1\" Type=\"http://schemas.openxmlformats.org/officeDocument/2006/relationships/worksheet\" Target=\"worksheets/sheet1.xml\"/><Relationship Id=\"rId2\" Type=\"http://schemas.openxmlformats.org/officeDocument/2006/relationships/worksheet\" Target=\"worksheets/sheet2.xml\"/><Relationship Id=\"rId3\" Type=\"http://schemas.openxmlformats.org/officeDocument/2006/relationships/worksheet\" Target=\"worksheets/sheet3.xml\"/><Relationship Id=\"rId4\" Type=\"http://schemas.openxmlformats.org/officeDocument/2006/relationships/worksheet\" Target=\"worksheets/sheet4.xml\"/><Relationship Id=\"rId5\" Type=\"http://schemas.openxmlformats.org/officeDocument/2006/relationships/styles\" Target=\"styles.xml\"/></Relationships>";}
            static string Styles(){return "<?xml version=\"1.0\" encoding=\"UTF-8\"?><styleSheet xmlns=\"http://schemas.openxmlformats.org/spreadsheetml/2006/main\"><numFmts count=\"1\"><numFmt numFmtId=\"164\" formatCode=\"yyyy-mm-dd hh:mm:ss.000\"/></numFmts><fonts count=\"1\"><font><sz val=\"11\"/><name val=\"Calibri\"/></font></fonts><fills count=\"1\"><fill><patternFill patternType=\"none\"/></fill></fills><borders count=\"1\"><border/></borders><cellStyleXfs count=\"1\"><xf numFmtId=\"0\" fontId=\"0\" fillId=\"0\" borderId=\"0\"/></cellStyleXfs><cellXfs count=\"2\"><xf numFmtId=\"0\" fontId=\"0\" fillId=\"0\" borderId=\"0\" xfId=\"0\"/><xf numFmtId=\"164\" fontId=\"0\" fillId=\"0\" borderId=\"0\" xfId=\"0\" applyNumberFormat=\"1\"/></cellXfs></styleSheet>";}
            public void Dispose(){foreach(XmlWriter w in new[]{main,alarm,policy,meta})if(w!=null){try{w.WriteEndElement();w.WriteEndDocument();}catch{}try{w.Dispose();}catch{}}if(z!=null){try{string[] entries={"xl/worksheets/sheet1.xml","xl/worksheets/sheet2.xml","xl/worksheets/sheet3.xml","xl/worksheets/sheet4.xml"};for(int i=0;i<entries.Length;i++){ZipArchiveEntry e=z.CreateEntry(entries[i],CompressionLevel.Optimal);using(Stream dst=e.Open())using(FileStream srcFile=File.OpenRead(sheetFiles[i]))srcFile.CopyTo(dst);}}finally{try{z.Dispose();}catch{}z=null;}}foreach(string f in sheetFiles)try{if(File.Exists(f))File.Delete(f);}catch{}}
        }
    }
}
